from pydantic import ValidationError
from app.ai.decision import decide_action
from app.ai.provider import AIProvider
from app.domain import (
    RecoveryCaseContext, DiagnosisResult, DecisionResult, 
    RootCauseCategory, RecoveryActionType
)
from app.models import CaseType, CaseStatus
from app.policy import evaluate_policy

class MockDecisionProvider(AIProvider):
    def __init__(self, action: RecoveryActionType, params: dict, mock_hallucination=False):
        self.action = action
        self.params = params
        self.mock_hallucination = mock_hallucination

    def ask_structured(self, prompt: str, response_schema):
        # Allow invalid schemas to be generated if hallucinating, to test pydantic validation
        if self.mock_hallucination:
            return response_schema.model_validate({
                "recommended_action": self.action,
                "action_parameters": self.params,
                "confidence_score": 0.9,
                "reasoning": "I am hallucinating"
            })
            
        return response_schema(
            recommended_action=self.action,
            action_parameters=self.params,
            confidence_score=0.9,
            reasoning="Valid reasoning"
        )

def get_base_case() -> RecoveryCaseContext:
    return RecoveryCaseContext(
        id="case_test_decision",
        case_type=CaseType.CHECKOUT_ABANDONED,
        status=CaseStatus.OPEN,
        amount_paise=100000,
        currency="INR",
        customer_id="cust_1",
        raw_signal_payload={},
        retry_count=0,
        cumulative_discount_paise=0
    )

def get_base_diagnosis() -> DiagnosisResult:
    return DiagnosisResult(
        root_cause_category=RootCauseCategory.FRICTION,
        specific_reason="drop_off",
        confidence_score=0.9,
        reasoning="Test"
    )

def test_decision_result_structural_validation():
    # Valid
    res = DecisionResult(
        recommended_action=RecoveryActionType.OFFER_DISCOUNT,
        action_parameters={"discount_percent": 10},
        confidence_score=0.9,
        reasoning="test"
    )
    assert res.recommended_action == RecoveryActionType.OFFER_DISCOUNT
    
    # Invalid: Missing parameter
    try:
        DecisionResult(
            recommended_action=RecoveryActionType.OFFER_DISCOUNT,
            action_parameters={}, # Missing discount_percent
            confidence_score=0.9,
            reasoning="test"
        )
        assert False, "Should fail validation"
    except ValidationError:
        pass
        
    # Invalid: Wrong parameter type
    try:
        DecisionResult(
            recommended_action=RecoveryActionType.RETRY_CHARGE,
            action_parameters={"delay_hours": "two"}, # string instead of int
            confidence_score=0.9,
            reasoning="test"
        )
        assert False, "Should fail validation"
    except ValidationError:
        pass

def test_decide_action_and_policy_integration():
    case = get_base_case()
    diagnosis = get_base_diagnosis()
    
    # 1. Valid Decision generated by AI
    provider = MockDecisionProvider(RecoveryActionType.OFFER_DISCOUNT, {"discount_percent": 10})
    decision = decide_action(case, diagnosis, provider)
    
    assert decision.recommended_action == RecoveryActionType.OFFER_DISCOUNT
    
    # 2. Passed into Policy Engine (Should Allow)
    policy_result = evaluate_policy(case, decision)
    assert policy_result.allowed is True
    assert policy_result.approved_decision is not None
    assert policy_result.approved_decision.idempotency_key is not None
    
    # 3. AI Hallucinates a 50% discount (Violating prompt instructions)
    provider_hallucinating = MockDecisionProvider(RecoveryActionType.OFFER_DISCOUNT, {"discount_percent": 50})
    bad_decision = decide_action(case, diagnosis, provider_hallucinating)
    
    # 4. Policy Engine strictly blocks it
    policy_result = evaluate_policy(case, bad_decision)
    assert policy_result.allowed is False
    assert "exceeds policy maximum" in policy_result.reason
    assert policy_result.approved_decision is None

if __name__ == "__main__":
    test_decision_result_structural_validation()
    test_decide_action_and_policy_integration()
    print("SUCCESS: Decision engine tests passed.")
