"""Add pending decision and session id

Revision ID: 1c8c796c1bdc
Revises: c91d2e3f4a05
Create Date: 2026-08-30 13:48:13.817484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c8c796c1bdc'
down_revision: Union[str, Sequence[str], None] = 'c91d2e3f4a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('pending_decision_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('recovery_cases', sa.Column('pending_diagnosis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('recovery_cases', sa.Column('session_id', sa.String(length=255), nullable=True))
    op.create_index('ix_recovery_cases_session_id', 'recovery_cases', ['session_id'], unique=True, postgresql_where=sa.text('session_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recovery_cases_session_id', table_name='recovery_cases', postgresql_where=sa.text('session_id IS NOT NULL'))
    op.drop_column('recovery_cases', 'session_id')
    op.drop_column('recovery_cases', 'pending_diagnosis_json')
    op.drop_column('recovery_cases', 'pending_decision_json')
    # ### end Alembic commands ###
