"""add_active_diagnosis_column

Revision ID: 4fee91cd09e4
Revises: 6e3c0fcbf43c
Create Date: 2026-08-28 15:28:29.503119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fee91cd09e4'
down_revision: Union[str, Sequence[str], None] = '6e3c0fcbf43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('active_diagnosis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'active_diagnosis')
    # ### end Alembic commands ###
