"""Add ui visibility columns

Revision ID: 6a89ee1c9229
Revises: 1c8c796c1bdc
Create Date: 2026-08-30 15:03:57.948743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a89ee1c9229'
down_revision: Union[str, Sequence[str], None] = '1c8c796c1bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('latest_diagnosis_category', sa.String(length=50), nullable=True))
    op.add_column('recovery_cases', sa.Column('latest_diagnosis_reasoning', sa.String(length=500), nullable=True))
    op.add_column('recovery_cases', sa.Column('latest_action_recommended', sa.String(length=50), nullable=True))
    op.add_column('recovery_cases', sa.Column('latest_comms_preview', sa.String(length=500), nullable=True))
    op.add_column('recovery_cases', sa.Column('cumulative_comms_cost_paise', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'cumulative_comms_cost_paise')
    op.drop_column('recovery_cases', 'latest_comms_preview')
    op.drop_column('recovery_cases', 'latest_action_recommended')
    op.drop_column('recovery_cases', 'latest_diagnosis_reasoning')
    op.drop_column('recovery_cases', 'latest_diagnosis_category')
    # ### end Alembic commands ###
