"""add_state_tracking_columns

Revision ID: 6e3c0fcbf43c
Revises: 
Create Date: 2026-08-28 15:22:53.930754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e3c0fcbf43c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('recovery_cases', sa.Column('cumulative_discount_paise', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('recovery_cases', 'raw_signal_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recovery_cases', 'raw_signal_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('recovery_cases', 'cumulative_discount_paise')
    op.drop_column('recovery_cases', 'retry_count')
    # ### end Alembic commands ###
