"""remove_active_diagnosis

Revision ID: 948e0f799ac8
Revises: b8ad0914f966
Create Date: 2026-08-29 14:30:57.853730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '948e0f799ac8'
down_revision: Union[str, Sequence[str], None] = 'b8ad0914f966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'active_diagnosis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('active_diagnosis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
