"""add_razorpay_event_id

Revision ID: a37f5603038e
Revises: 7f5c34296d64
Create Date: 2026-08-29 00:49:47.785520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37f5603038e'
down_revision: Union[str, Sequence[str], None] = '7f5c34296d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('razorpay_event_id', sa.String(length=255), nullable=True))
    op.create_index('ix_recovery_cases_razorpay_event_id', 'recovery_cases', ['razorpay_event_id'], unique=True, postgresql_where=sa.text('razorpay_event_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recovery_cases_razorpay_event_id', table_name='recovery_cases', postgresql_where=sa.text('razorpay_event_id IS NOT NULL'))
    op.drop_column('recovery_cases', 'razorpay_event_id')
    # ### end Alembic commands ###
