"""add_awaiting_payment_status

Revision ID: a54c435d9b0d
Revises: a37f5603038e
Create Date: 2026-08-29 11:43:43.102802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54c435d9b0d'
down_revision: Union[str, Sequence[str], None] = 'a37f5603038e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE casestatus ADD VALUE IF NOT EXISTS 'AWAITING_PAYMENT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
