"""Add priority_score

Revision ID: b8ad0914f966
Revises: a54c435d9b0d
Create Date: 2026-08-29 13:23:52.103534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ad0914f966'
down_revision: Union[str, Sequence[str], None] = 'a54c435d9b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('priority_score', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_recovery_cases_priority_score'), 'recovery_cases', ['priority_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_cases_priority_score'), table_name='recovery_cases')
    op.drop_column('recovery_cases', 'priority_score')
    # ### end Alembic commands ###
